"""Add biography to Author and other changes

Revision ID: 004e973ce08b
Revises: e9cd7286cce8
Create Date: 2024-07-20 10:54:53.749424

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '004e973ce08b'
down_revision = 'e9cd7286cce8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('authors', schema=None) as batch_op:
        batch_op.add_column(sa.Column('biography', sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('authors', schema=None) as batch_op:
        batch_op.drop_column('biography')

    # ### end Alembic commands ###
