"""Add image_url to authors

Revision ID: e9cd7286cce8
Revises: ac05c1b3a6a1
Create Date: 2024-07-20 09:09:09.467588

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e9cd7286cce8'
down_revision = 'ac05c1b3a6a1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('authors', schema=None) as batch_op:
        batch_op.add_column(sa.Column('image_url', sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('authors', schema=None) as batch_op:
        batch_op.drop_column('image_url')

    # ### end Alembic commands ###
